### 1- Escribe un programa que mediante indexación en NumPy sea capaz de invertir un arreglo (donde el primer elemento se convierte en el último)

In [7]:
import numpy as np

In [3]:
invert_arr = np.arange(0,21)
invert_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
invert_arr[::-1]  # [start:end:stepsize] invertimos los valores del arreglo

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

In [6]:
# tambien podemos usar flip()

np.flip(invert_arr)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

### 2- Escribe un programa con NumPy para convertir valores de grados Fahrenheit a grados centigrados. Los valores se almacenan en un arreglo de salida.

In [20]:
arr_far_cent = np.array([0, 12, 45.21, 34, 99.91, 32])
arr_far_cent = arr_far_cent.astype(float)

In [23]:
arr_cent = ((arr_far_cent - 32) / 1.8).round(2)
arr_cent

array([-17.78, -11.11,   7.34,   1.11,  37.73,   0.  ])

### 3.Escribe un programa con NumPy para encontrar la unión de dos arreglos. La unión debe devolver un arreglo ordenado de valores que están en cualquiera de los dos arreglos de entrada (sin repetición).

In [27]:
arreglo1 = np.array([0,10,20])
arreglo2 = np.array([20,10,30])

In [42]:
arr_union = np.concatenate((arreglo1, arreglo2))

In [44]:
arr_union

array([ 0, 10, 20, 20, 10, 30])

In [47]:
arr_ordenado = np.sort(arr_union)
arr_result = np.unique(arr_ordenado)
arr_result

array([ 0, 10, 20, 30])